# CodeRabbit configuration
# Docs: https://docs.coderabbit.ai/

reviews:
  auto_review:
    enabled: true

  high_level_summary: false
  auto_title_placeholder: ""   # empty = disable auto-title trigger
  # poem: false  # if you use poems and want to disable them too
  poem: false
