version: "2"

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0

linters:
  exclusions:
    # Exclude entire paths from linting
    paths:
      - '(.+)_test\.go$'
      - 'testdata/'
      - '(_generated|\.pb|mock_.*)\.go$'
    rules:
      # Exclude test helpers from style checks
      - path: '(testing|helpers)\.go$'
        linters:
          - revive
          - gocritic
    # Common false positives
    text-rules:
      - text: "unused-parameter"
        linters:
          - revive
      - text: "package-comments"
        linters:
          - revive
  disable-all: true
  enable:
    # Correctness / bugs
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    # Style & maintainability (lightweight)
    - revive
    - gocritic
    - misspell

formatters:
  enable:
    - gofumpt
    - gci

linters-settings:
  errcheck:
    # Don't require checking these ubiquitous funcs
    exclude-functions:
      - (*io.Closer).Close
      - (net/http.(*Response)).Body.Close
      - (fmt.*).Print*
  revive:
    # Keep this small; add rules as the team agrees
    rules:
      - name: exported
        disabled: true  # Don't require comments on all exports
      - name: unreachable-code
      - name: indent-error-flow
      - name: early-return
      - name: if-return
      - name: blank-imports
      - name: unnecessary-stmt
  gocritic:
    disabled-checks:
      - hugeParam
      - commentFormatting
    enabled-tags:
      - diagnostic
      - performance
      - style
  gofumpt:
    extra-rules: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/aledsdavies/opal)
    skip-generated: true

# Speed up by skipping heavy dirs
skip-dirs:
  - vendor
  - third_party
  - tools
